#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_exclusions.star", "exclusions")

#@ if exclusions.is_pkg_enabled("kpack.community.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: kpack
  namespace: app-platform-install
  annotations:
    kapp.k14s.io/change-group: "kpack"
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: app-platform-install-sa
  packageRef:
    refName: kpack.community.tanzu.vmware.com
    versionSelection:
      constraints: 0.5.0
      prereleases: {}
  values:
  - secretRef:
      name: kpack-values
---
apiVersion: v1
kind: Secret
metadata:
  name: kpack-values
  namespace: app-platform-install
stringData:
  values.yaml: #@ yaml.encode(data.values.kpack)

#@ end
