release:
    version: v0.10.0
images:
    all:
        repository: projects-stg.registry.vmware.com/tkg/cluster-api
    cert-manager:
        repository: projects-stg.registry.vmware.com/tkg
        tag: v1.1.0_vmware.1
providers:
    - name: cluster-api
      url: /Users/csamp/.config/tanzu/tkg/providers/cluster-api/v0.3.23/core-components.yaml
      type: CoreProvider
    - name: aws
      url: /Users/csamp/.config/tanzu/tkg/providers/infrastructure-aws/v0.6.6/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: vsphere
      url: /Users/csamp/.config/tanzu/tkg/providers/infrastructure-vsphere/v0.7.10/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: azure
      url: /Users/csamp/.config/tanzu/tkg/providers/infrastructure-azure/v0.4.15/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: tkg-service-vsphere
      url: /Users/csamp/.config/tanzu/tkg/providers/infrastructure-tkg-service-vsphere/v1.1.0/unused.yaml
      type: InfrastructureProvider
    - name: kubeadm
      url: /Users/csamp/.config/tanzu/tkg/providers/bootstrap-kubeadm/v0.3.23/bootstrap-components.yaml
      type: BootstrapProvider
    - name: kubeadm
      url: /Users/csamp/.config/tanzu/tkg/providers/control-plane-kubeadm/v0.3.23/control-plane-components.yaml
      type: ControlPlaneProvider
    - name: docker
      url: /Users/csamp/.config/tanzu/tkg/providers/infrastructure-docker/v0.3.23/infrastructure-components.yaml
      type: InfrastructureProvider
