---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: app-platform.community.tanzu.vmware.com.0.1.0
spec:
  refName: app-platform.community.tanzu.vmware.com
  version: 0.1.0
  releasedAt: 2022-02-01T14:53:24Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: "index.docker.io/csamp/app-platform-package-bundle:0.1.0"
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        excluded_packages:
          type: array
          default: []
          items:
            type: string
          description:
            "A list of package refs that should be excluded from app-platform"
        contour:
          type: object
          default: {}
          description: "contour values"
        kpack:
          type: object
          default: {}
          description: "kpack values"
        knative_serving:
          type: object
          default: {}
          description: "knative-serving values"
