
contour:
  envoy:
    service:
      type: ClusterIP
    hostPorts:
      enable: true

knative_serving:
  domain:
    type: real
    name: 127-0-0-1.sslip.io

kpack:
  # name of registry secret where build artifacts are stored
  registry:
    url: https://index.docker.io/v1/
    username: csamp
    password: S0fitel4$
  builder:
    # path to the container repository where kpack build artifacts are stored
    tag: csamp/builder
  # A comma-separated list of languages e.g. [java,nodejs] that will be supported for development
  # Allowed values are:
  # - java
  # - nodejs
  # - dotnet-core
  # - go
  # - ruby
  # - php
  languages: [java]

supply_chain:
  image_prefix: csamp/



